// dashboard-data.ts — AMBU & DBU Learning Dashboard (2025-2026)
// GENERATED — do not hand-edit. PII-free aggregates only.
export const meta = {
  "yearsCovered": [
    2024,
    2025,
    2026
  ],
  "source": "Consolidated master (LMS learning hours + Forms/Qualtrics feedback)",
  "grainNote": "learningHours attribute-sliceable; feedback anonymous session-level (do NOT slice by BU/person).",
  "note": "VIP feedback pending."
} as const;
export const kpis = {
  "totalLearningHours": 9918.0,
  "totalCompletions": 1557,
  "uniqueLearners": 912,
  "programsCount": 12,
  "feedbackResponses": 1305,
  "avgSatisfaction": 4.6,
  "completionRatePct": 76.3,
  "learningHoursByBU": {
    "AMBU": 5884.0,
    "DBU": 4010.0,
    "Unknown": 24.0
  },
  "completionsByBU": {
    "AMBU": 1052,
    "DBU": 502,
    "Unknown": 3
  },
  "uniqueLearnersByBU": {
    "AMBU": 559,
    "DBU": 350,
    "Unknown": 3
  }
} as const;
export const programs = [
  {
    "code": "SLP",
    "displayName": "Self Leadership Program",
    "year": 2025,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": true
  },
  {
    "code": "SLII",
    "displayName": "Situational Leadership II (SLII)",
    "year": 2025,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": true
  },
  {
    "code": "L2H",
    "displayName": "License to Hire",
    "year": 2025,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": false,
    "hasExtras": true
  },
  {
    "code": "TEN",
    "displayName": "The Essential Negotiator",
    "year": 2025,
    "buScope": "AMBU",
    "hasFeedback": false,
    "hasEligibility": false,
    "hasExtras": false
  },
  {
    "code": "VIP",
    "displayName": "VIP Clienteling",
    "year": 2025,
    "buScope": "DBU",
    "hasFeedback": true,
    "hasEligibility": false,
    "hasExtras": true
  },
  {
    "code": "2026:MAFP_Psychological_Safety",
    "displayName": "4 stages of psychological safety",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:MAFP_Rise_Mall_management",
    "displayName": "RISE Mall Management Program",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:MAF_AMBU_Path",
    "displayName": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:MAF_AMBU_Resilience_Sessions",
    "displayName": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:MAF_DBU_6Thinking_Hats",
    "displayName": "6 Thinking Hats Workshop",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:MAF_DBU_Lean_Fundamentals",
    "displayName": "Lean Fundamentals Workshop",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  },
  {
    "code": "2026:Managing_Virtual_Effectively",
    "displayName": "Managing Virtual Teams Effectively",
    "year": 2026,
    "buScope": "AMBU+DBU",
    "hasFeedback": true,
    "hasEligibility": true,
    "hasExtras": false
  }
];
export const learningHours = [
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 12,
    "totalHours": 60.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 17,
    "totalHours": 85.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 2,
    "totalHours": 10.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 14,
    "totalHours": 70.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 8,
    "totalHours": 40.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 8,
    "totalHours": 40.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 14,
    "totalHours": 70.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 5,
    "totalHours": 25.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 4,
    "totalHours": 20.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 1,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 2,
    "totalHours": 10.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 1,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 10,
    "totalHours": 50.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 12,
    "totalHours": 60.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "4 stages of psychological safety",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 26,
    "totalHours": 130.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "The 4 Stages of Psychological Safety™ - AMBU UAE",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 5,
    "totalHours": 25.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "The 4 Stages of Psychological Safety™ - AMBU UAE",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 3,
    "totalHours": 15.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "The 4 Stages of Psychological Safety™ - AMBU UAE",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 30.0
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "program": "The 4 Stages of Psychological Safety™ - AMBU UAE",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-07",
    "completions": 8,
    "totalHours": 40.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 5,
    "totalHours": 10.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 10,
    "totalHours": 20.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 10,
    "totalHours": 20.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 13,
    "totalHours": 26.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 5,
    "totalHours": 10.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 4,
    "totalHours": 8.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 9,
    "totalHours": 18.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 5,
    "totalHours": 10.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 10,
    "totalHours": 20.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-07",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 16,
    "totalHours": 32.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 11,
    "totalHours": 22.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 17,
    "totalHours": 34.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-07",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "program": "RISE Mall Management Program",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-07",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-01",
    "completions": 4,
    "totalHours": 8.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 13,
    "totalHours": 26.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "N/A",
    "month": "2026-05",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-01",
    "completions": 8,
    "totalHours": 16.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 13,
    "totalHours": 26.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "program": "PATH: Own Your Career Growth Journey",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 10,
    "totalHours": 20.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Expert",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 1.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 2,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 3,
    "totalHours": 3.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 3,
    "totalHours": 3.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 3,
    "totalHours": 3.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 5,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 1.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 3,
    "totalHours": 3.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 13,
    "totalHours": 13.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "N/A",
    "month": "2026-06",
    "completions": 2,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Customer Ambassador",
    "month": "2026-06",
    "completions": 1,
    "totalHours": 1.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 26,
    "totalHours": 26.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "N/A",
    "month": "2026-06",
    "completions": 4,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 12,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 1.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "program": "Resilience in Uncertain Times online sessions",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "N/A",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 1.0
  },
  {
    "programCode": "2026:MAF_DBU_6Thinking_Hats",
    "program": "6 Thinking Hats Workshop",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 8,
    "totalHours": 24.0
  },
  {
    "programCode": "2026:MAF_DBU_6Thinking_Hats",
    "program": "6 Thinking Hats Workshop",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 9,
    "totalHours": 27.0
  },
  {
    "programCode": "2026:MAF_DBU_Lean_Fundamentals",
    "program": "Lean Fundamentals Workshop",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 1,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:MAF_DBU_Lean_Fundamentals",
    "program": "Lean Fundamentals Workshop",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-05",
    "completions": 6,
    "totalHours": 30.0
  },
  {
    "programCode": "2026:MAF_DBU_Lean_Fundamentals",
    "program": "Lean Fundamentals Workshop",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-05",
    "completions": 1,
    "totalHours": 5.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Expert",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 3,
    "totalHours": 6.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-03",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 4,
    "totalHours": 8.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 1,
    "totalHours": 2.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-03",
    "completions": 2,
    "totalHours": 4.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 4,
    "totalHours": 8.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-04",
    "completions": 4,
    "totalHours": 8.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-03",
    "completions": 6,
    "totalHours": 12.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "program": "Managing Virtual Teams Effectively",
    "year": 2026,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-04",
    "completions": 9,
    "totalHours": 18.0
  },
  {
    "programCode": "L2H",
    "program": "License to Hire",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 2,
    "totalHours": 14.0
  },
  {
    "programCode": "L2H",
    "program": "License to Hire",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 6,
    "totalHours": 42.0
  },
  {
    "programCode": "L2H",
    "program": "License to Hire",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 6,
    "totalHours": 42.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2024-12",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2024-12",
    "completions": 6,
    "totalHours": 48.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Business Leader",
    "month": "2024-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2024-11",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 12,
    "totalHours": 96.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Business Leader",
    "month": "2024-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2024-11",
    "completions": 23,
    "totalHours": 184.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2024-12",
    "completions": 4,
    "totalHours": 32.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-10",
    "completions": 11,
    "totalHours": 88.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 45,
    "totalHours": 360.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-12",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "Oman",
    "role": "Business Leader",
    "month": "2024-11",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "Oman",
    "role": "Expert",
    "month": "2024-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2024-11",
    "completions": 6,
    "totalHours": 48.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Business Leader",
    "month": "2024-10",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2024-11",
    "completions": 7,
    "totalHours": 56.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2024-12",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-10",
    "completions": 17,
    "totalHours": 136.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-11",
    "completions": 39,
    "totalHours": 312.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-12",
    "completions": 4,
    "totalHours": 32.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Expert",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2025-05",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2025-05",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2025-06",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-06",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 10,
    "totalHours": 80.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-06",
    "completions": 12,
    "totalHours": 96.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Team Leader",
    "month": "2025-06",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 3,
    "totalHours": 24.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-05",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 8,
    "totalHours": 64.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-05",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 8,
    "totalHours": 64.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-05",
    "completions": 3,
    "totalHours": 24.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Business Leader",
    "month": "2025-02",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Expert",
    "month": "2025-02",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 7,
    "totalHours": 56.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 4,
    "totalHours": 32.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-05",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 13,
    "totalHours": 104.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-05",
    "completions": 6,
    "totalHours": 48.0
  },
  {
    "programCode": "SLII",
    "program": "Situational Leadership II (SLII)",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 5,
    "totalHours": 40.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 25,
    "totalHours": 200.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "N/A",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-08",
    "completions": 47,
    "totalHours": 376.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 8,
    "totalHours": 64.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "N/A",
    "month": "2025-08",
    "completions": 3,
    "totalHours": 24.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-08",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 10,
    "totalHours": 80.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Lebanon",
    "role": "Team Leader",
    "month": "2025-07",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 37,
    "totalHours": 296.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-07",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Customer Ambassador",
    "month": "2025-06",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Customer Ambassador",
    "month": "2025-07",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Customer Ambassador",
    "month": "2025-10",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-06",
    "completions": 55,
    "totalHours": 440.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 55,
    "totalHours": 440.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-08",
    "completions": 39,
    "totalHours": 312.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-09",
    "completions": 27,
    "totalHours": 216.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-10",
    "completions": 11,
    "totalHours": 88.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "N/A",
    "month": "2025-06",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "N/A",
    "month": "2025-07",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-06",
    "completions": 6,
    "totalHours": 48.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-07",
    "completions": 3,
    "totalHours": 24.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-08",
    "completions": 8,
    "totalHours": 64.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-09",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-10",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-08",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 15,
    "totalHours": 120.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "Egypt",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 24,
    "totalHours": 192.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-07",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-06",
    "completions": 54,
    "totalHours": 432.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 19,
    "totalHours": 152.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-08",
    "completions": 27,
    "totalHours": 216.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-09",
    "completions": 28,
    "totalHours": 224.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-10",
    "completions": 23,
    "totalHours": 184.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-08",
    "completions": 2,
    "totalHours": 16.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-09",
    "completions": 3,
    "totalHours": 24.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "Unknown",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-07",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "Unknown",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-08",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2025,
    "bu": "Unknown",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-09",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2026-06",
    "completions": 6,
    "totalHours": 48.0
  },
  {
    "programCode": "SLP",
    "program": "Self Leadership Program",
    "year": 2026,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2026-06",
    "completions": 1,
    "totalHours": 8.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 16.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "Bahrain",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 16.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 16.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "Oman",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 1,
    "totalHours": 16.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-11",
    "completions": 12,
    "totalHours": 192.0
  },
  {
    "programCode": "TEN",
    "program": "The Essential Negotiator",
    "year": 2025,
    "bu": "AMBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-11",
    "completions": 8,
    "totalHours": 128.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2024-10",
    "completions": 14,
    "totalHours": 196.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2024,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2024-10",
    "completions": 6,
    "totalHours": 77.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-02",
    "completions": 13,
    "totalHours": 91.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-05",
    "completions": 11,
    "totalHours": 132.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Individual Contributor",
    "month": "2025-09",
    "completions": 17,
    "totalHours": 238.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-02",
    "completions": 5,
    "totalHours": 35.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-05",
    "completions": 5,
    "totalHours": 60.0
  },
  {
    "programCode": "VIP",
    "program": "VIP Clienteling",
    "year": 2025,
    "bu": "DBU",
    "country": "United Arab Emirates",
    "role": "Team Leader",
    "month": "2025-09",
    "completions": 5,
    "totalHours": 70.0
  }
];
export const feedback = [
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 1 - West Region",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 15,
    "satisfaction": 4.6,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 2 - West Region",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 13,
    "satisfaction": 4.6,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 3 - AMBU UAE",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 11,
    "satisfaction": 4.7,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 3 - DBU UAE",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 11,
    "satisfaction": 4.6,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 4 - AMBU Oman",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 16,
    "satisfaction": 4.8,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 4 - DBU UAE",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 12,
    "satisfaction": 4.2,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.1,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 5 - AMBU UAE",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 13,
    "satisfaction": 4.6,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 5 - DBU UAE",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 15,
    "satisfaction": 4.1,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.3,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 6 - AMBU UAE",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 10,
    "satisfaction": 4.4,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 6 - DBU UAE",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 12,
    "satisfaction": 4.4,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 7 - AMBU UAE",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 11,
    "satisfaction": 4.9,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "sessionLabel": "The 4 Stages of Psychological Safety - Cohort 8 - AMBU UAE",
    "sessionPart": "Full session",
    "month": "2026-07",
    "responses": 10,
    "satisfaction": 4.6,
    "objectivesClarity": null,
    "facilitatorEffectiveness": 4.5,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 1",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 20,
    "satisfaction": 4.6,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": 4.6,
    "recommendation": 4.8,
    "recommendationRatePct": 95.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 2 - Part 1",
    "sessionPart": "Part 1",
    "month": "2026-04",
    "responses": 21,
    "satisfaction": 4.6,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": 4.5,
    "recommendation": 4.7,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 2 - Part 2",
    "sessionPart": "Part 2",
    "month": "2026-04",
    "responses": 23,
    "satisfaction": 4.5,
    "objectivesClarity": 4.5,
    "facilitatorEffectiveness": 4.5,
    "confidenceApplication": 4.4,
    "recommendation": 4.7,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 3 - Part 1",
    "sessionPart": "Part 1",
    "month": "2026-05",
    "responses": 20,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": 4.8,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 3 - Part 2",
    "sessionPart": "Part 2",
    "month": "2026-05",
    "responses": 19,
    "satisfaction": 4.5,
    "objectivesClarity": 4.5,
    "facilitatorEffectiveness": 4.5,
    "confidenceApplication": 4.5,
    "recommendation": 4.6,
    "recommendationRatePct": 89.5
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 4 - Full session",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 21,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": 4.7,
    "recommendation": 4.9,
    "recommendationRatePct": 95.2
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 5 - Full session",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 20,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": 4.7,
    "recommendation": 4.7,
    "recommendationRatePct": 95.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 6 - Lead to Deal",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 22,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": 4.6,
    "recommendation": 4.7,
    "recommendationRatePct": 95.5
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 7 - Deal to Lease",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 20,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": 4.8,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "sessionLabel": "RISE Session 8 - Lease to Trade",
    "sessionPart": "Full session",
    "month": "2026-07",
    "responses": 22,
    "satisfaction": 4.8,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.9,
    "recommendation": 5.0,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "sessionLabel": "PATH Employees Session 1 - 2026-05-18",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 5,
    "satisfaction": 4.8,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": 4.8,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "sessionLabel": "PATH Session 1 - 2025-12-04",
    "sessionPart": "Full session",
    "month": "2025-12",
    "responses": 14,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": 4.8,
    "recommendation": 4.9,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "sessionLabel": "PATH Session 2 - 2026-01-28",
    "sessionPart": "Full session",
    "month": "2026-01",
    "responses": 11,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.7,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "sessionLabel": "PATH Session 3 - 2026-04-13",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 11,
    "satisfaction": 5.0,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.7,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "sessionLabel": "PATH Session 4 - 2026-05-06",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 26,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": 4.8,
    "recommendation": 4.7,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "sessionLabel": "Resilience - Full session",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 31,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.6,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "sessionLabel": "Resilience - Full session",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 43,
    "satisfaction": 4.5,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": 4.5,
    "recommendation": 4.8,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_DBU_6Thinking_Hats",
    "sessionLabel": "6 Thinking Hats - Full session",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 13,
    "satisfaction": 4.7,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.5,
    "recommendation": 4.9,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_DBU_Lean_Fundamentals",
    "sessionLabel": "Lean Fundamentals - Full session",
    "sessionPart": "Full session",
    "month": "2026-05",
    "responses": 7,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": 4.7,
    "recommendation": 4.9,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "sessionLabel": "Managing Virtual Teams - Full session",
    "sessionPart": "Full session",
    "month": "2026-03",
    "responses": 8,
    "satisfaction": 4.6,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": 4.5,
    "recommendation": 4.9,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "sessionLabel": "Managing Virtual Teams - Full session",
    "sessionPart": "Full session",
    "month": "2026-04",
    "responses": 24,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": 4.9,
    "recommendation": 5.0,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "L2H",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2025-11",
    "responses": 9,
    "satisfaction": 4.7,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2024-11",
    "responses": 102,
    "satisfaction": 4.7,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2024-12",
    "responses": 21,
    "satisfaction": 4.8,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2025-02",
    "responses": 62,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2025-05",
    "responses": 14,
    "satisfaction": 4.6,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 19,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLII",
    "sessionLabel": "",
    "sessionPart": "Full session",
    "month": "2025-11",
    "responses": 8,
    "satisfaction": 4.8,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": null
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-06-23|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 18,
    "satisfaction": 4.0,
    "objectivesClarity": 4.5,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-06-24|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 24,
    "satisfaction": 4.7,
    "objectivesClarity": 4.5,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-06-25|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 13,
    "satisfaction": 4.1,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 90.9
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-06-26|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 11,
    "satisfaction": 4.6,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-06-30|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-06",
    "responses": 21,
    "satisfaction": 4.4,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 90.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-08|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 13,
    "satisfaction": 4.5,
    "objectivesClarity": 4.2,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-10|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 21,
    "satisfaction": 4.5,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-14|Oman",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 13,
    "satisfaction": 4.8,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-14|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 22,
    "satisfaction": 4.7,
    "objectivesClarity": 4.4,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-15|Oman",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 16,
    "satisfaction": 4.3,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 93.3
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-16|Oman",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 27,
    "satisfaction": 4.8,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-16|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 19,
    "satisfaction": 4.9,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-07-22|Lebanon",
    "sessionPart": "Full session",
    "month": "2025-07",
    "responses": 8,
    "satisfaction": 4.8,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-10|Egypt",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 21,
    "satisfaction": 4.0,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 94.4
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-18|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 13,
    "satisfaction": 4.2,
    "objectivesClarity": 4.5,
    "facilitatorEffectiveness": 4.5,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 90.9
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-19|Egypt",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 33,
    "satisfaction": 4.6,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 93.8
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-20|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 18,
    "satisfaction": 4.4,
    "objectivesClarity": 4.4,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-26|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 23,
    "satisfaction": 4.5,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-08-28|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-08",
    "responses": 20,
    "satisfaction": 4.9,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-09-08|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-09",
    "responses": 7,
    "satisfaction": 4.7,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-09-22|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-09",
    "responses": 14,
    "satisfaction": 4.2,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.6,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 84.6
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-09-29|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-09",
    "responses": 18,
    "satisfaction": 4.3,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-10-23|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-10",
    "responses": 8,
    "satisfaction": 4.5,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 66.7
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-10-29|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2025-10",
    "responses": 14,
    "satisfaction": 4.6,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 4.7,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-11-06|Bahrain",
    "sessionPart": "Full session",
    "month": "2025-11",
    "responses": 28,
    "satisfaction": 4.9,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.8,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-11-17|Egypt",
    "sessionPart": "Full session",
    "month": "2025-11",
    "responses": 11,
    "satisfaction": 5.0,
    "objectivesClarity": 5.0,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2025-11-18|Egypt",
    "sessionPart": "Full session",
    "month": "2025-11",
    "responses": 14,
    "satisfaction": 4.5,
    "objectivesClarity": 4.9,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "SLP",
    "sessionLabel": "MAFP_Self_Leadership_Workshop|2026-06-10|United Arab Emirates",
    "sessionPart": "Full session",
    "month": "2026-06",
    "responses": 7,
    "satisfaction": 4.4,
    "objectivesClarity": 4.7,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "VIP",
    "sessionLabel": "Advanced CX - Cohort 1",
    "sessionPart": "Full session",
    "month": null,
    "responses": 13,
    "satisfaction": 4.6,
    "objectivesClarity": 4.4,
    "facilitatorEffectiveness": 4.5,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "VIP",
    "sessionLabel": "Advanced CX - Cohort 2",
    "sessionPart": "Full session",
    "month": null,
    "responses": 8,
    "satisfaction": 4.8,
    "objectivesClarity": 4.6,
    "facilitatorEffectiveness": 5.0,
    "confidenceApplication": null,
    "recommendation": null,
    "recommendationRatePct": 100.0
  },
  {
    "programCode": "VIP",
    "sessionLabel": "Introduction to VIP Clienteling - Cohort 1",
    "sessionPart": "Full session",
    "month": null,
    "responses": 8,
    "satisfaction": 4.1,
    "objectivesClarity": 4.1,
    "facilitatorEffectiveness": 4.4,
    "confidenceApplication": null,
    "recommendation": 3.9,
    "recommendationRatePct": null
  },
  {
    "programCode": "VIP",
    "sessionLabel": "Introduction to VIP Clienteling - Cohort 2",
    "sessionPart": "Full session",
    "month": null,
    "responses": 8,
    "satisfaction": 4.1,
    "objectivesClarity": 4.1,
    "facilitatorEffectiveness": 4.2,
    "confidenceApplication": null,
    "recommendation": 4.1,
    "recommendationRatePct": null
  },
  {
    "programCode": "VIP",
    "sessionLabel": "Observation Debrief Course - Main",
    "sessionPart": "Full session",
    "month": null,
    "responses": 8,
    "satisfaction": 4.8,
    "objectivesClarity": 4.8,
    "facilitatorEffectiveness": 4.9,
    "confidenceApplication": null,
    "recommendation": 4.9,
    "recommendationRatePct": null
  }
];
export const completion = [
  {
    "programCode": "2026:MAFP_Psychological_Safety",
    "eligible": 209,
    "completedEligible": 155,
    "completionRatePct": 74.2
  },
  {
    "programCode": "2026:MAFP_Rise_Mall_management",
    "eligible": 27,
    "completedEligible": 27,
    "completionRatePct": 100.0
  },
  {
    "programCode": "2026:MAF_AMBU_Path",
    "eligible": 109,
    "completedEligible": 36,
    "completionRatePct": 33.0
  },
  {
    "programCode": "2026:MAF_AMBU_Resilience_Sessions",
    "eligible": 285,
    "completedEligible": 115,
    "completionRatePct": 40.4
  },
  {
    "programCode": "2026:MAF_DBU_6Thinking_Hats",
    "eligible": 27,
    "completedEligible": 16,
    "completionRatePct": 59.3
  },
  {
    "programCode": "2026:MAF_DBU_Lean_Fundamentals",
    "eligible": 19,
    "completedEligible": 8,
    "completionRatePct": 42.1
  },
  {
    "programCode": "2026:Managing_Virtual_Effectively",
    "eligible": 37,
    "completedEligible": 37,
    "completionRatePct": 100.0
  },
  {
    "programCode": "SLII",
    "eligible": 337,
    "completedEligible": 315,
    "completionRatePct": 93.5
  },
  {
    "programCode": "SLP",
    "eligible": 595,
    "completedEligible": 546,
    "completionRatePct": 91.8
  }
];
export const extras = [
  {
    "programCode": "L2H",
    "metric": "Catering",
    "mean": 4.22,
    "n": 9
  },
  {
    "programCode": "L2H",
    "metric": "Engaged/Informed",
    "mean": 4.67,
    "n": 9
  },
  {
    "programCode": "L2H",
    "metric": "Facilitator Listening",
    "mean": 4.67,
    "n": 9
  },
  {
    "programCode": "L2H",
    "metric": "Valuable",
    "mean": 4.56,
    "n": 9
  },
  {
    "programCode": "L2H",
    "metric": "Venue",
    "mean": 4.56,
    "n": 9
  },
  {
    "programCode": "SLII",
    "metric": "Catering",
    "mean": 4.31,
    "n": 226
  },
  {
    "programCode": "SLII",
    "metric": "Engaged/Informed",
    "mean": 4.76,
    "n": 226
  },
  {
    "programCode": "SLII",
    "metric": "Facilitator Listening",
    "mean": 4.8,
    "n": 226
  },
  {
    "programCode": "SLII",
    "metric": "Valuable",
    "mean": 4.78,
    "n": 226
  },
  {
    "programCode": "SLII",
    "metric": "Venue",
    "mean": 4.61,
    "n": 226
  },
  {
    "programCode": "SLP",
    "metric": "Avg Skill After",
    "mean": 4.39,
    "n": 394
  },
  {
    "programCode": "SLP",
    "metric": "Avg Skill Before",
    "mean": 2.96,
    "n": 432
  },
  {
    "programCode": "SLP",
    "metric": "Engagement",
    "mean": 3.96,
    "n": 471
  },
  {
    "programCode": "SLP",
    "metric": "Perf Increase",
    "mean": 0.98,
    "n": 443
  },
  {
    "programCode": "VIP",
    "metric": "Admin Satisfied",
    "mean": 4.81,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Apply Knowledge",
    "mean": 0.9,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Knowledge/Skills",
    "mean": 4.48,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Materials Depth",
    "mean": 4.19,
    "n": 16
  },
  {
    "programCode": "VIP",
    "metric": "Share Knowledge",
    "mean": 0.95,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Trainer Engaged",
    "mean": 4.9,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Trainer Enhanced",
    "mean": 4.57,
    "n": 21
  },
  {
    "programCode": "VIP",
    "metric": "Trainer Knowledgeable",
    "mean": 4.5,
    "n": 24
  },
  {
    "programCode": "VIP",
    "metric": "Venue",
    "mean": 4.86,
    "n": 21
  }
];
