export type MetricPage = 'Overview' | 'Programs' | 'Learners & Reach' | 'Feedback' | 'Eligibility' | 'Quality Signals'

export type MetricDoc = {
  id: string
  title: string
  page: MetricPage
  summary: string
  calculation: string
  interpretation: string
  scope: string
  caveat?: string
}

export const metricDocs: MetricDoc[] = [
  { id: 'learning-hours', title: 'Learning hours', page: 'Overview', summary: 'Total time participants spent in learning activities.', calculation: 'Sum of recorded total hours for rows in the current filter.', interpretation: 'Use this to understand delivery volume. Compare it with learners and completions to judge scale and depth.', scope: 'Year, month, business unit, country, role, and program filters apply.', caveat: 'Hours measure participation time, not learning quality or business impact.' },
  { id: 'completions', title: 'Total completions', page: 'Overview', summary: 'Number of recorded course or program completions.', calculation: 'Sum of completion records in the learning-hours dataset.', interpretation: 'A higher count means more learning instances were finished. Read alongside eligible completion rate where a target population exists.', scope: 'All delivery filters apply.', caveat: 'One learner can complete more than one course, so completions are not unique people.' },
  { id: 'unique-learners', title: 'Unique learners', page: 'Learners & Reach', summary: 'Distinct learners represented in the privacy-safe reach data.', calculation: 'Program cards use authoritative cross-session distinct totals where supplied. Filtered slices and monthly views use the available program, month, BU, country, and role aggregates.', interpretation: 'Use program-card totals for the deduplicated audience of recurring programs; use filtered reach as a directional slice.', scope: 'All learner-reach filters apply. Authoritative program totals are used only when no country, role, or month filter is active.', caveat: 'Monthly and demographic aggregates are non-additive. Without person-level identifiers, they cannot be safely deduplicated across groups or months.' },
  { id: 'active-programs', title: 'Programs active', page: 'Overview', summary: 'Programs with delivery in the selected scope.', calculation: 'Count of programs represented by filtered learning-hours rows; without a year filter, the full program catalogue is shown.', interpretation: 'Shows breadth of the active portfolio, not program effectiveness.', scope: 'Year and business-unit selections affect this count.', caveat: 'A program needs only one in-scope delivery row to be counted as active.' },
  { id: 'avg-satisfaction', title: 'Average satisfaction', page: 'Feedback', summary: 'Average participant satisfaction, shown on a common 1–5 scale for comparison.', calculation: 'Response-weighted average. Psychological Safety scores are collected on 0–10 and divided by two for the normalized 1–5 display; PS program cards also show the native 0–10 value.', interpretation: 'Higher is better. Treat normalized scores as comparison aids and use the native PS score for source-scale interpretation.', scope: 'Feedback supports time and program filtering; some demographic filters may not apply.', caveat: 'Normalization does not change the source response, but it can hide differences in response behavior between survey scales.' },
  { id: 'satisfaction-rate', title: 'Satisfaction rate', page: 'Feedback', summary: 'Share of responses in the top two positive answer categories.', calculation: 'Response-weighted average of each source survey’s top-two-box rate on its native scale.', interpretation: 'Higher means a larger share of respondents selected a strongly positive rating.', scope: 'Uses the available feedback grain and current supported filters.', caveat: 'Thresholds follow each survey’s native scale, so use average satisfaction for the most consistent cross-program comparison.' },
  { id: 'feedback-responses', title: 'Feedback responses', page: 'Feedback', summary: 'Number of survey responses behind the feedback measures.', calculation: 'Sum of responses across filtered feedback rows.', interpretation: 'Use this to judge confidence in averages. Larger samples are generally more stable.', scope: 'Feedback filters apply where dimensions exist.', caveat: 'Responses are not necessarily unique learners and may not represent all participants.' },
  { id: 'completion-rate', title: 'Eligible completion rate', page: 'Eligibility', summary: 'Share of the eligible target population that completed the program.', calculation: 'Completed eligible participants ÷ eligible participants × 100.', interpretation: 'Higher means more of the intended audience completed. The dashboard uses green at 80%+, amber at 60–79%, and red below 60% as visual guideposts, not universal targets.', scope: 'Calculated within the available eligibility rows for program, BU, country, and role.', caveat: 'Do not compare this directly with total completions: the denominator is only people on an eligibility list.' },
  { id: 'hours-by-bu', title: 'Learning hours by BU', page: 'Overview', summary: 'How total learning time is distributed across business units.', calculation: 'Learning hours grouped by business unit.', interpretation: 'Use the share to see where delivery is concentrated; compare with population size before inferring coverage.', scope: 'All delivery filters apply.', caveat: 'Unknown means the source data did not provide a mapped business unit.' },
  { id: 'hours-by-month', title: 'Hours by month', page: 'Overview', summary: 'Monthly learning delivery volume, split by business unit.', calculation: 'Learning hours summed by month and BU.', interpretation: 'Use peaks and gaps to understand seasonality, campaign timing, and delivery cadence.', scope: 'All delivery filters apply.', caveat: 'The chart shows activity timing, not whether later learning caused business outcomes.' },
  { id: 'program-contribution', title: 'Program contribution', page: 'Overview', summary: 'Programs ranked by their contribution to total learning hours.', calculation: 'Learning hours summed by program and sorted from highest to lowest.', interpretation: 'Highlights which programs drive portfolio volume.', scope: 'All delivery filters apply.', caveat: 'High volume does not by itself mean high quality, reach, or impact.' },
  { id: 'country-breakdown', title: 'Country breakdown', page: 'Overview', summary: 'Learning hours and completions delivered in each country.', calculation: 'Hours and completion records summed by country.', interpretation: 'Use this to compare geographic delivery footprint.', scope: 'All delivery filters apply.', caveat: 'Compare with local workforce size before interpreting relative coverage.' },
  { id: 'program-card', title: 'Program card measures', page: 'Programs', summary: 'A compact view of delivery volume, reach, satisfaction, and eligible completion.', calculation: 'Hours and completions are summed; learners use reach aggregates; satisfaction is response weighted and normalized; completion uses the eligibility list.', interpretation: 'Open a card to inspect trends and supporting measures before making decisions.', scope: 'Program cards respect supported global filters.', caveat: 'The measures come from datasets with different grains and should not be added together.' },
  { id: 'role-mix', title: 'Role mix', page: 'Learners & Reach', summary: 'Distribution of learner reach across job roles.', calculation: 'Unique-learner aggregates grouped by role.', interpretation: 'Shows which roles receive the most reach and where representation may be lower.', scope: 'All learner-reach filters apply.', caveat: 'Aggregated unique counts may overlap across months and programs.' },
  { id: 'monthly-reach', title: 'Monthly reach curve', page: 'Learners & Reach', summary: 'Learner reach recorded in each month.', calculation: 'Unique-learner aggregates summed by month; undated rows are excluded.', interpretation: 'Use this to identify changes in monthly reach and delivery cadence.', scope: 'All learner-reach filters apply.', caveat: 'This is monthly reach, not a cumulative deduplicated audience.' },
  { id: 'country-role-hours', title: 'Country × role heatmap', page: 'Learners & Reach', summary: 'Learning hours for each country and role combination.', calculation: 'Learning hours summed for each country-role cell. Darker cells represent more hours relative to the largest visible cell.', interpretation: 'Use this to spot concentrations and potential coverage gaps.', scope: 'All delivery filters apply.', caveat: 'Color is relative to the current view and does not represent a fixed target.' },
  { id: 'learner-depth', title: 'Learner depth', page: 'Learners & Reach', summary: 'Estimated distribution of average learning hours per learner.', calculation: 'For each matching aggregate row: total hours ÷ unique learners, then learners are placed into hour bands.', interpretation: 'Use this as a directional view of learning intensity.', scope: 'Uses matching reach and hours rows under current filters.', caveat: 'This is an estimate from aggregated data, not a person-level distribution. It should not be used to assess individual learning time.' },
  { id: 'facilitator', title: 'Facilitator rating', page: 'Feedback', summary: 'Average participant rating of facilitation quality on a 1–5 scale.', calculation: 'Response-weighted average of available facilitator ratings.', interpretation: 'Higher scores suggest participants viewed facilitation more positively.', scope: 'Only programs collecting this question contribute.', caveat: 'Missing programs are excluded; compare response counts and survey context.' },
  { id: 'confidence', title: 'Confidence / commitment', page: 'Feedback', summary: 'Average self-reported confidence or commitment after learning.', calculation: 'Response-weighted average of available 1–5 survey items.', interpretation: 'Higher values indicate stronger participant-reported readiness or intent.', scope: 'Only programs collecting a comparable item contribute.', caveat: 'Intent and confidence are leading indicators, not proof of behavior change.' },
  { id: 'recommend-rate', title: 'Recommend rate', page: 'Feedback', summary: 'Share of respondents who would recommend the learning experience.', calculation: 'Response-weighted average of available recommendation rates.', interpretation: 'Higher means stronger participant advocacy.', scope: 'Only programs with a recommendation item contribute.', caveat: 'This is not the same as NPS unless responses are captured and scored with the NPS method.' },
  { id: 'nps', title: 'Net Promoter Score (NPS)', page: 'Feedback', summary: 'Advocacy score ranging from −100 to +100.', calculation: 'Percentage of promoters (9–10) minus percentage of detractors (0–6). Passives (7–8) affect neither side.', interpretation: 'Positive means promoters outnumber detractors; use trend and sample size rather than a single universal benchmark.', scope: 'Only valid NPS survey responses contribute.', caveat: 'NPS is sensitive to sample size and survey context and should not be converted to a 1–5 average.' },
  { id: 'satisfaction-distribution', title: 'Satisfaction distribution', page: 'Feedback', summary: 'Number of feedback sessions in each satisfaction band.', calculation: 'Session-level average satisfaction is normalized to 1–5 and assigned to a band.', interpretation: 'Shows whether the overall average hides a wide spread of experiences.', scope: 'Current supported feedback filters apply.', caveat: 'Bars count aggregated feedback rows or sessions, not individual responses.' },
  { id: 'feedback-comparison', title: 'Program feedback comparison', page: 'Feedback', summary: 'Side-by-side quality measures by program.', calculation: 'Each measure is response weighted within program; satisfaction is normalized where needed.', interpretation: 'Use this to identify relative strengths and questions for follow-up.', scope: 'Only programs with the relevant question appear.', caveat: 'Differences may reflect survey design, audience, timing, and sample size.' },
  { id: 'satisfaction-trend', title: 'Monthly satisfaction trend', page: 'Feedback', summary: 'How average satisfaction changes over time.', calculation: 'Response-weighted average satisfaction by month, normalized to 1–5.', interpretation: 'Look for sustained movement rather than reacting to one month.', scope: 'Undated feedback is excluded from the monthly line.', caveat: 'Small monthly samples can create volatility.' },
  { id: 'eligible', title: 'Eligible population', page: 'Eligibility', summary: 'People identified as the intended audience for a program.', calculation: 'Sum of eligible counts from program eligibility lists.', interpretation: 'This is the denominator for eligible completion and helps size the target audience.', scope: 'Program, BU, country, and role filters apply where available.', caveat: 'Eligibility definitions may differ by program and are not the same as the total workforce.' },
  { id: 'completed-eligible', title: 'Completed eligible', page: 'Eligibility', summary: 'Eligible people who completed the assigned program.', calculation: 'Sum of completed-eligible counts from eligibility records.', interpretation: 'Shows how many intended participants were reached to completion.', scope: 'Program, BU, country, and role filters apply.', caveat: 'Excludes completions by people outside the eligibility list.' },
  { id: 'eligibility-funnel', title: 'Eligible vs completed', page: 'Eligibility', summary: 'Target population and completed target population by program.', calculation: 'Eligible and completed-eligible counts grouped by program.', interpretation: 'The gap between bars is the remaining eligible audience not recorded as completed.', scope: 'Eligibility filters apply.', caveat: 'The chart does not show whether incomplete learners started or never enrolled.' },
  { id: 'eligibility-breakdowns', title: 'Eligibility breakdowns', page: 'Eligibility', summary: 'Eligible completion by program, BU, and role.', calculation: 'Completed eligible ÷ eligible within each displayed group.', interpretation: 'Use this to locate groups with stronger completion or larger remaining populations.', scope: 'Eligibility filters apply.', caveat: 'Small groups can produce unstable percentages; inspect counts as well as rates.' },
  { id: 'skill-uplift', title: 'Skill uplift', page: 'Quality Signals', summary: 'Change between participants’ before- and after-learning skill ratings.', calculation: 'Net uplift = after score − before score. Relative uplift = net uplift ÷ before score × 100.', interpretation: 'Positive uplift suggests improved self-reported capability.', scope: 'Only programs with comparable before/after questions contribute.', caveat: 'Self-reported uplift is not an objective skills assessment and may be affected by response shift.' },
  { id: 'likert-signals', title: 'Likert quality signals', page: 'Quality Signals', summary: 'Average agreement with quality, confidence, or application statements.', calculation: 'Response-weighted average on the displayed Likert scale, usually 1–5.', interpretation: 'Higher is generally more positive; read the exact question before comparing measures.', scope: 'Only records with the relevant item contribute.', caveat: 'Different questions are not interchangeable even when they use the same scale.' },
  { id: 'rate-signals', title: 'Rate-based quality signals', page: 'Quality Signals', summary: 'Percentage of respondents meeting a defined positive threshold.', calculation: 'Positive responses ÷ valid responses × 100.', interpretation: 'Higher means more respondents met the stated threshold.', scope: 'Only valid responses to that item contribute.', caveat: 'Threshold definitions can vary; use the detailed label and sample size.' },
  { id: 'sample-size', title: 'Sample size (n)', page: 'Quality Signals', summary: 'Number of responses used to calculate a measure.', calculation: 'Count of valid responses available for the specific item.', interpretation: 'Larger samples usually provide a more stable signal. Always read a score together with n.', scope: 'Varies by question because respondents may skip items.', caveat: 'A large sample can still be unrepresentative if response bias is present.' },
  { id: 'undated-sessions', title: 'Undated sessions', page: 'Feedback', summary: 'Feedback records with no reliable session month.', calculation: 'Count or summary of feedback rows where the source date is missing.', interpretation: 'These records still contribute to overall feedback, but not to monthly trends.', scope: 'Shown where undated records are relevant.', caveat: 'Do not infer when these sessions occurred.' },
]

export const metricDocById = Object.fromEntries(metricDocs.map((item) => [item.id, item])) as Record<string, MetricDoc>

export const metricPages: MetricPage[] = ['Overview', 'Programs', 'Learners & Reach', 'Feedback', 'Eligibility', 'Quality Signals']
