export type MetricPage = 'Overview' | 'Programs' | 'Learners & Reach' | 'Feedback' | 'Eligibility' | 'Quality Signals' | 'Mandatory Learning'

export type MetricDoc = {
  id: string
  title: string
  page: MetricPage
  summary: string
  calculation: string
  interpretation: string
  scope: string
  caveat?: string
}

export const metricDocs: MetricDoc[] = [
  { id: 'learning-hours', title: 'Learning hours', page: 'Overview', summary: 'The total time people spent learning across all activities.', calculation: 'We add up the recorded hours for everything in your current view.', interpretation: 'A measure of how much learning is happening. Read it next to learner and completion counts to see both scale and depth.', scope: 'Responds to the year, month, business unit, country, role, and program filters.', caveat: 'This counts time spent, not how good the learning was or the results it drove.' },
  { id: 'completions', title: 'Total completions', page: 'Overview', summary: 'How many courses or programs were finished.', calculation: 'We count every completion record in your current view.', interpretation: 'More completions means more learning was seen through to the end. Where there is a target audience, read it next to the eligible completion rate.', scope: 'Responds to all delivery filters.', caveat: 'One person can finish several courses, so this is not a headcount of individual people.' },
  { id: 'unique-learners', title: 'Unique learners', page: 'Learners & Reach', summary: 'The number of distinct people reached, based on privacy-safe data.', calculation: 'Program cards use verified people-counts that remove duplicates across sessions. Filtered and monthly views use the available program, month, business unit, country, and role summaries.', interpretation: 'Use the program-card totals for a true, de-duplicated headcount of recurring programs. Treat filtered views as a rough guide rather than an exact count.', scope: 'Responds to all Learners & Reach filters. Verified totals are used only when no country, role, or month filter is active.', caveat: 'Monthly and demographic figures cannot be added together. Without individual IDs, the same person may be counted in more than one group or month.' },
  { id: 'active-programs', title: 'Programs active', page: 'Overview', summary: 'Programs that had any delivery in your current view.', calculation: 'We count the programs that appear in your filtered data. With no year selected, we show the full program catalogue.', interpretation: 'Shows how broad the active portfolio is — not how well programs performed.', scope: 'Responds to the year and business-unit selections.', caveat: 'A single session in view is enough for a program to count as active.' },
  { id: 'avg-satisfaction', title: 'Average satisfaction', page: 'Feedback', summary: 'The average satisfaction rating, shown on a shared 1–5 scale so programs can be compared fairly.', calculation: 'An average that gives busier surveys more weight. Psychological Safety is collected on a 0–10 scale and halved to fit the 1–5 view; its program cards also show the original 0–10 score.', interpretation: 'Higher is better. Use the shared 1–5 score to compare programs, and the original Psychological Safety score when you want its true scale.', scope: 'Supports time and program filters. Some demographic filters may not apply.', caveat: 'Rescaling does not change anyone’s answer, but it can mask differences in how people respond to different survey scales.' },
  { id: 'satisfaction-rate', title: 'Satisfaction rate', page: 'Feedback', summary: 'The share of answers that landed in the two most positive options.', calculation: 'An average — weighted by how many people responded — of each survey’s “top two answers” rate on its own scale.', interpretation: 'Higher means more people chose a strongly positive rating.', scope: 'Uses the available feedback detail and current supported filters.', caveat: 'Each survey uses its own scale to set the threshold, so use average satisfaction for the most consistent program-to-program comparison.' },
  { id: 'feedback-responses', title: 'Feedback responses', page: 'Feedback', summary: 'How many survey responses sit behind the feedback numbers.', calculation: 'We add up the responses across your filtered feedback.', interpretation: 'Use this to judge how much to trust the averages — bigger samples are steadier.', scope: 'Responds to feedback filters where the detail exists.', caveat: 'Responses are not necessarily unique people and may not cover everyone who took part.' },
  { id: 'completion-rate', title: 'Eligible completion rate', page: 'Eligibility', summary: 'The share of the intended audience who completed the program.', calculation: 'Eligible people who completed ÷ all eligible people × 100.', interpretation: 'Higher means more of the intended audience finished. The dashboard shades 80%+ green, 60–79% amber, and below 60% red as visual guides — not fixed targets. Click any program bar to filter to that program.', scope: 'Calculated within the available eligibility data for program, business unit, country, and role.', caveat: 'Do not compare this with total completions — it only counts people on an eligibility list.' },
  { id: 'hours-by-bu', title: 'Learning hours by BU', page: 'Overview', summary: 'How total learning time splits across business units.', calculation: 'Learning hours grouped by business unit.', interpretation: 'Use the split to see where delivery is concentrated. Compare with team sizes before judging coverage.', scope: 'Responds to all delivery filters.', caveat: '“Unknown” means the source data did not say which business unit it belonged to.' },
  { id: 'hours-by-month', title: 'Hours by month', page: 'Overview', summary: 'Learning delivered each month, split by business unit.', calculation: 'Learning hours added up by month and business unit.', interpretation: 'Use the peaks and quiet spells to understand seasonality, campaign timing, and delivery rhythm.', scope: 'Responds to all delivery filters.', caveat: 'This shows when activity happened, not whether later learning caused business results.' },
  { id: 'program-contribution', title: 'Program contribution', page: 'Overview', summary: 'Programs ranked by how much they add to total learning hours.', calculation: 'Learning hours added up by program, highest to lowest.', interpretation: 'Shows which programs drive the most volume. Click any bar to filter to that program.', scope: 'Responds to all delivery filters.', caveat: 'High volume alone does not mean high quality, reach, or impact.' },
  { id: 'country-breakdown', title: 'Country breakdown', page: 'Overview', summary: 'Learning hours and completions delivered in each country.', calculation: 'Hours and completions added up by country.', interpretation: 'Use it to compare where delivery is happening geographically.', scope: 'Responds to all delivery filters.', caveat: 'Compare with local team sizes before reading too much into coverage.' },
  { id: 'program-card', title: 'Program card measures', page: 'Programs', summary: 'A quick snapshot of a program’s volume, reach, satisfaction, and eligible completion.', calculation: 'Hours and completions are totalled; learner counts come from reach data; satisfaction is weighted by responses and rescaled to 1–5; completion uses the eligibility list.', interpretation: 'Open a card to explore its trends and supporting numbers before making a call.', scope: 'Respects the supported global filters.', caveat: 'These numbers come from different data sources and should not be added together.' },
  { id: 'role-mix', title: 'Role mix', page: 'Learners & Reach', summary: 'How learner reach is spread across job roles.', calculation: 'Unique-learner counts grouped by role.', interpretation: 'Shows which roles are reached most, and where representation may be thinner.', scope: 'Responds to all Learners & Reach filters.', caveat: 'These counts can overlap across months and programs.' },
  { id: 'monthly-reach', title: 'Monthly reach curve', page: 'Learners & Reach', summary: 'How many learners were reached each month.', calculation: 'Unique-learner counts added up by month; entries with no date are left out.', interpretation: 'Use it to spot changes in monthly reach and delivery rhythm.', scope: 'Responds to all Learners & Reach filters.', caveat: 'This is reach per month, not a running de-duplicated audience.' },
  { id: 'country-role-hours', title: 'Country × role heatmap', page: 'Learners & Reach', summary: 'Learning hours for every country-and-role combination.', calculation: 'Learning hours totalled for each country/role cell. Darker cells mean more hours relative to the busiest cell shown.', interpretation: 'Use it to spot concentrations and possible coverage gaps.', scope: 'Responds to all delivery filters.', caveat: 'Shading is relative to what is on screen now, not a fixed target.' },
  { id: 'learner-depth', title: 'Learner depth', page: 'Learners & Reach', summary: 'An estimate of how many hours each learner typically spends.', calculation: 'For each matching group: total hours ÷ number of learners, then learners are sorted into hour bands.', interpretation: 'Use it as a rough read on how intensive the learning is.', scope: 'Uses matching reach and hours data under current filters.', caveat: 'This is an estimate from grouped data, not individual records — do not use it to judge any one person’s learning time.' },
  { id: 'facilitator', title: 'Facilitator rating', page: 'Feedback', summary: 'The average rating people gave the facilitation, on a 1–5 scale.', calculation: 'An average of the available facilitator ratings, weighted by responses.', interpretation: 'Higher scores suggest people felt more positive about how sessions were led.', scope: 'Only programs that ask this question are included.', caveat: 'Programs without the question are left out — check response counts and context when comparing.' },
  { id: 'confidence', title: 'Confidence / commitment', page: 'Feedback', summary: 'How confident or committed people felt after learning, on average.', calculation: 'An average of the available 1–5 survey answers, weighted by responses.', interpretation: 'Higher means people reported feeling more ready or more committed to act.', scope: 'Only programs asking a comparable question are included.', caveat: 'Confidence and intent point the way forward, but they are not proof that behaviour changed.' },
  { id: 'recommend-rate', title: 'Recommend rate', page: 'Feedback', summary: 'The share of people who would recommend the learning.', calculation: 'An average of the available recommendation rates, weighted by responses.', interpretation: 'Higher means stronger word-of-mouth support from participants.', scope: 'Only programs with a recommendation question are included.', caveat: 'This is not the same as NPS unless the responses were captured and scored the NPS way.' },
  { id: 'nps', title: 'Net Promoter Score (NPS)', page: 'Feedback', summary: 'Net Promoter Score — an advocacy score from −100 to +100.', calculation: 'Percentage of promoters (9–10) minus percentage of detractors (0–6). Passives (7–8) do not count toward either side.', interpretation: 'A positive score means promoters outnumber detractors. Watch the trend and sample size rather than a single benchmark.', scope: 'Only valid NPS responses are included.', caveat: 'NPS is sensitive to sample size and survey context, and should not be converted into a 1–5 average.' },
  { id: 'satisfaction-distribution', title: 'Satisfaction distribution', page: 'Feedback', summary: 'How many feedback sessions fall into each satisfaction band.', calculation: 'Each session’s average satisfaction is rescaled to 1–5 and placed in a band.', interpretation: 'Shows whether a single average is hiding a wide range of experiences.', scope: 'Responds to the supported feedback filters.', caveat: 'Bars count grouped feedback sessions, not individual responses.' },
  { id: 'feedback-comparison', title: 'Program feedback comparison', page: 'Feedback', summary: 'Quality measures placed side by side, program by program.', calculation: 'Each measure is weighted by responses within its program; satisfaction is rescaled to 1–5 where needed.', interpretation: 'Use it to spot relative strengths and questions worth following up.', scope: 'Only programs that asked the relevant question appear.', caveat: 'Differences can come from survey design, audience, timing, and sample size — not just performance.' },
  { id: 'satisfaction-trend', title: 'Monthly satisfaction trend', page: 'Feedback', summary: 'How average satisfaction shifts over time.', calculation: 'Average satisfaction by month, weighted by responses and rescaled to 1–5.', interpretation: 'Look for a sustained direction rather than reacting to any single month.', scope: 'Feedback with no date is left out of the monthly line.', caveat: 'Small monthly samples can swing the line around.' },
  { id: 'eligible', title: 'Eligible population', page: 'Eligibility', summary: 'The people identified as a program’s intended audience.', calculation: 'The eligible counts from program eligibility lists, added together.', interpretation: 'This is the base for the eligible completion rate and shows how big the target audience is.', scope: 'Responds to program, business unit, country, and role filters where available.', caveat: 'Eligibility is defined per program and is not the same as the whole workforce.' },
  { id: 'completed-eligible', title: 'Completed eligible', page: 'Eligibility', summary: 'Eligible people who completed the program they were assigned.', calculation: 'The completed-eligible counts from eligibility records, added together.', interpretation: 'Shows how many of the intended audience were carried through to completion.', scope: 'Responds to program, business unit, country, and role filters.', caveat: 'Does not count completions by people who were not on the eligibility list.' },
  { id: 'eligibility-funnel', title: 'Eligible vs completed', page: 'Eligibility', summary: 'The target audience and how many of them completed, by program.', calculation: 'Eligible and completed-eligible counts grouped by program.', interpretation: 'The gap between the bars is the eligible audience not yet recorded as complete. Click any program name to filter to it.', scope: 'Responds to eligibility filters.', caveat: 'It does not show whether the unfinished learners started or never signed up.' },
  { id: 'eligibility-breakdowns', title: 'Eligibility breakdowns', page: 'Eligibility', summary: 'Eligible completion rates by program, business unit, and role.', calculation: 'Completed-eligible ÷ eligible within each group shown.', interpretation: 'Use it to find groups with strong completion or large audiences still to reach.', scope: 'Responds to eligibility filters.', caveat: 'Small groups can produce jumpy percentages — check the counts alongside the rates.' },
  { id: 'skill-uplift', title: 'Skill uplift', page: 'Quality Signals', summary: 'The change between people’s before- and after-learning skill ratings.', calculation: 'Net uplift = after score − before score. Relative uplift = net uplift ÷ before score × 100.', interpretation: 'Positive uplift suggests people felt more capable after the learning.', scope: 'Only programs with comparable before/after questions are included.', caveat: 'This is self-reported, not an objective skills test, and can be affected by how people re-judge themselves after learning.' },
  { id: 'likert-signals', title: 'Likert quality signals', page: 'Quality Signals', summary: 'Average agreement with statements about quality, confidence, or applying what was learned.', calculation: 'An average on the scale shown (usually 1–5), weighted by responses.', interpretation: 'Higher is generally more positive — read the exact statement before comparing measures.', scope: 'Only records with the relevant question are included.', caveat: 'Different questions are not interchangeable, even on the same scale.' },
  { id: 'rate-signals', title: 'Rate-based quality signals', page: 'Quality Signals', summary: 'The share of people who cleared a set positive threshold.', calculation: 'Positive responses ÷ valid responses × 100.', interpretation: 'Higher means more people met the stated bar.', scope: 'Only valid responses to that question are included.', caveat: 'The threshold can differ between questions — check the label and sample size.' },
  { id: 'sample-size', title: 'Sample size (n)', page: 'Quality Signals', summary: 'How many responses a number is based on.', calculation: 'A count of the valid responses available for that specific question.', interpretation: 'Bigger samples usually give a steadier signal. Always read a score together with its sample size.', scope: 'Varies by question, since people can skip items.', caveat: 'Even a big sample can mislead if the people who responded are not representative.' },
  { id: 'undated-sessions', title: 'Undated sessions', page: 'Feedback', summary: 'Feedback with no reliable session month.', calculation: 'A count or summary of feedback where the source date is missing.', interpretation: 'These still count toward overall feedback, just not the monthly trend.', scope: 'Shown where undated records are relevant.', caveat: 'Do not try to guess when these sessions happened.' },
  { id: 'mandatory-assigned', title: 'Total assigned', page: 'Mandatory Learning', summary: 'How many people were assigned a mandatory course.', calculation: 'We add up every assignment record in your current view.', interpretation: 'This is the base for both completed and pending — read the other measures as a share of this number.', scope: 'Responds to the BU, course, status, and country filters.', caveat: 'One person can be assigned more than one mandatory course, so this is not a headcount of unique people.' },
  { id: 'mandatory-completed', title: 'Completed', page: 'Mandatory Learning', summary: 'How many assigned people finished the mandatory course.', calculation: 'We add up completion records in your current view.', interpretation: 'Higher is better. Read it next to total assigned to judge how much of the audience is actually done.', scope: 'Responds to the BU, course, status, and country filters.', caveat: 'This counts completions, not how well the material was understood.' },
  { id: 'mandatory-pending', title: 'Pending', page: 'Mandatory Learning', summary: 'How many assigned people have not yet completed the mandatory course.', calculation: 'Total assigned minus completed, so it can never contradict the other two numbers.', interpretation: 'This is the follow-up list — the gap still to close before full compliance.', scope: 'Responds to the BU, course, status, and country filters.', caveat: 'Pending does not distinguish between someone who has not started and someone partway through.' },
  { id: 'mandatory-compliance-rate', title: 'Compliance rate', page: 'Mandatory Learning', summary: 'The share of assigned people who have completed the mandatory course.', calculation: 'Completed ÷ total assigned × 100.', interpretation: 'The dashboard shades 80%+ green, 60–79% amber, and below 60% red as visual guides — not fixed targets.', scope: 'Responds to the BU, course, status, and country filters.', caveat: 'A small assigned population can swing this percentage sharply — check the underlying counts too.' },
  { id: 'mandatory-by-course', title: 'Compliance by course', page: 'Mandatory Learning', summary: 'Completed vs pending headcount for each mandatory course, with its compliance rate.', calculation: 'Assignments are grouped by course; each bar shows completed and pending stacked, with the rate labelled.', interpretation: 'Use it to see which mandatory courses are furthest from full compliance.', scope: 'Responds to the BU, status, and country filters.', caveat: 'Courses with very few assignments can show a misleadingly high or low rate.' },
  { id: 'mandatory-by-entity', title: 'Business entity leaderboard', page: 'Mandatory Learning', summary: 'Business entities ranked by how many people still have a pending mandatory course.', calculation: 'Assignments are grouped by business entity and sorted by pending headcount, highest first.', interpretation: 'The entities at the top need the most follow-up. This view is aggregate-only — no individual names appear.', scope: 'Responds to the BU, course, status, and country filters.', caveat: 'AMBU/DBU is derived from Business Entity using a maintained mapping table; an unmapped entity shows as "Unknown".' },
  { id: 'mandatory-trend', title: 'Completion trend', page: 'Mandatory Learning', summary: 'Mandatory-course completions recorded each month, split by business unit.', calculation: 'Completions are added up by month, using the completion date, and grouped by business unit.', interpretation: 'Look for a sustained increase in completions over time rather than reacting to any single month.', scope: 'Responds to the BU filter. Course, status, and country do not apply to this monthly view.', caveat: 'This shows when completions were recorded, not when the assignment was originally issued.' },
]

export const metricDocById = Object.fromEntries(metricDocs.map((item) => [item.id, item])) as Record<string, MetricDoc>

// User interaction guide
export const interactiveChartGuide = 'On any chart that shows programs — Program contribution, the Eligibility funnel, and Completion rate — click a bar or program name to filter the whole dashboard to that program. It is the fastest way to drill into one program across every page.'

export const metricPages: MetricPage[] = ['Overview', 'Programs', 'Learners & Reach', 'Feedback', 'Eligibility', 'Quality Signals', 'Mandatory Learning']
